zuul:
  prefix: /users
  routes:
    user-register:
      path: /**
      url: http://user-register-ms:8080
    user-token-auth:
      path: /token/**
      url: http://user-token-auth-ms:8080
    test:
      path: /redirect/**
      url: http://google.com
ribbon:
  eureka:
    enabled: false
# payment-methods:
#   ribbon:
#     listOfServers: localhost:8081
